dictionary["en"] = {
    settings: "Settings",
    switch_language: "Switch language",
    reset_progress: "Reset progress",

    resource_group_assets : "Assets",
    resource_group_stats : "Attributes",
    resource_group_skills : "Skills",

    resource_money : "Euro",
    resource_time : "Time",
    resource_bottles : "Bottles",
    resource_energy : "Stamina",
    resource_local_knowledge : "Local knowledge",
    
    action_collect_bottles_name : "Collect returnable bottles",
    action_collect_bottles_description : "Some people are just too lazy to get their deposit for the bottles back. Lucky for you.",
    action_return_bottles_name : "Return bottles",
    action_return_bottles_description : "Done right returning the collected bottles can be quite lucrative.",
    action_beg_name : "Beg",
    action_beg_description : "The floor is hard and most people just walk by, but at least you don't have to walk.",
    action_sit_and_rest_name : "Sit on a bench",
    action_sit_and_rest_description : "Listening to the surrounding sounds and feeling the light breeze on your skin makes you feel refreshed.",
    action_rake_leaves_name : "Rake leaves",
    action_rake_leaves_description : "The gardens in the neighbourhood are full of leaves and an endless source of income. But it is an exhausting activity.",
    action_run_name : "Run",
    action_run_description : "Maybe you can finish a marathon one day if you are training long enough.",

    upgrade_second_hand_shop_name : "Second-hand shop",
    upgrade_second_hand_shop_description : "",
    upgrade_purse_name : "Wallet",
    upgrade_purse_description : "Doubles your money capacity",
    upgrade_shopping_cart_name : "Shopping cart",
    upgrade_shopping_cart_description : "This common cart made of metal allows you to carry up to 100 bottles with you.",
    upgrade_plan_your_route_name : "Plan your route",
    upgrade_plan_your_route_description : "By planning your route efficiently you finish collecting the bottles twice as fast.",
    upgrade_use_both_hands_name : "Use both hands",
    upgrade_use_both_hands_description : "By using both hands you can grab two bottles instead of just one.",
    upgrade_muscle_memory_collect_bottles_name : "Muscle Memory (Collect bottles)",
    upgrade_muscle_memory_collect_bottles_description : "You really know how to collect bottles and can do it without thinking about it.",
    upgrade_use_two_deposit_machines_name : "Use two deposit machines",
    upgrade_use_two_deposit_machines_description : "You found a place with two deposit machines next to each other and can return the bottles faster now.",
    upgrade_muscle_memory_return_bottles_name : "Muscle Memory (Return bottles)",
    upgrade_muscle_memory_return_bottles_description : "You really know how to put bottles in the deposit machine and can do it without thinking about it.",
    upgrade_science_lab_name : "Science lab",
    upgrade_science_lab_description : "",
    upgrade_prestige_name : "Prestige",
    upgrade_prestige_description : "",
    upgrade_multitasking_name : "Multitasking",
    upgrade_multitasking_description : "You can do one thing more simultanously.",
    upgrade_debug_unlock_all_name : "Debug: Unlock everything",
    upgrade_debug_unlock_all_description : "Unlocks all resources, actions and upgrades"
};